// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearMockLog(arg1) {
  return window['go']['main']['App']['ClearMockLog'](arg1);
}

export function CountFolderDescendants(arg1, arg2) {
  return window['go']['main']['App']['CountFolderDescendants'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteMockServer(arg1) {
  return window['go']['main']['App']['DeleteMockServer'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetMockLog(arg1) {
  return window['go']['main']['App']['GetMockLog'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListMockServers() {
  return window['go']['main']['App']['ListMockServers']();
}

export function MoveFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3);
}

export function MoveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2, arg3);
}

export function RunningMockServers() {
  return window['go']['main']['App']['RunningMockServers']();
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveMockServer(arg1) {
  return window['go']['main']['App']['SaveMockServer'](arg1);
}

export function SaveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2, arg3);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function StartMockServer(arg1) {
  return window['go']['main']['App']['StartMockServer'](arg1);
}

export function StopMockServer(arg1) {
  return window['go']['main']['App']['StopMockServer'](arg1);
}
