// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteMockServer(arg1) {
  return window['go']['main']['App']['DeleteMockServer'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetMockLog(arg1) {
  return window['go']['main']['App']['GetMockLog'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListMockServers() {
  return window['go']['main']['App']['ListMockServers']();
}

export function RunningMockServers() {
  return window['go']['main']['App']['RunningMockServers']();
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveMockServer(arg1) {
  return window['go']['main']['App']['SaveMockServer'](arg1);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function StartMockServer(arg1) {
  return window['go']['main']['App']['StartMockServer'](arg1);
}

export function StopMockServer(arg1) {
  return window['go']['main']['App']['StopMockServer'](arg1);
}
