// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:string):Promise<main.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteMockServer(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string,arg2:string):Promise<void>;

export function GetEnvironments():Promise<main.EnvironmentSet>;

export function GetMockLog(arg1:string):Promise<Array<main.MockLogEntry>>;

export function ListCollections():Promise<Array<main.Collection>>;

export function ListMockServers():Promise<Array<main.MockServer>>;

export function RunningMockServers():Promise<Record<string, number>>;

export function SaveEnvironment(arg1:main.Environment):Promise<main.Environment>;

export function SaveMockServer(arg1:main.MockServer):Promise<main.MockServer>;

export function SaveRequest(arg1:string,arg2:main.SavedRequest):Promise<main.SavedRequest>;

export function SendRequest(arg1:main.RequestInput):Promise<main.ResponseData>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function StartMockServer(arg1:string):Promise<void>;

export function StopMockServer(arg1:string):Promise<void>;
